#!/usr/bin/env python3
"""Capture sample NLP extraction output for 3 fixture types.

docs/05-integration-testing-and-delivery.md §7 (T-110)

Usage:
    python scripts/capture_sample_output.py --env dev [--job-id JOB_ID]

Queries DynamoDB for the most recent successfully processed candidates
matching:
    native_pdf   -> alice_johnson_native.pdf
    scanned_pdf  -> daniel_kim_scanned.pdf
    docx         -> bob_kumar.docx

Writes:
    docs/sample-nlp-output/native_pdf.json
    docs/sample-nlp-output/scanned_pdf.json
    docs/sample-nlp-output/docx.json

Each file contains:
    extracted_text       — from the stored DynamoDB item (truncated for display)
    extraction_metadata  — page count, file type, ocr_applied, etc.
    entities             — extracted skills, titles_held, name, email, experience
    method_per_field     — ner / hybrid_phrase_matcher / deterministic per field
    provenance           — job_id, candidate_id, original_filename, updated_at

The files are generated from REAL deployed run output and must not be
hand-edited (T-110 / docs/05-integration-testing-and-delivery.md §7).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

import boto3

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "docs" / "sample-nlp-output"
REGION = "ap-south-1"

# Which fixture -> output filename mapping
TARGETS = {
    "native_pdf": "alice_johnson_native.pdf",
    "scanned_pdf": "daniel_kim_scanned.pdf",
    "docx": "bob_kumar.docx",
}

# Method attribution per field (Architecture.md §8.1 method-honesty table)
METHOD_PER_FIELD = {
    "skills": "hybrid_phrase_matcher",
    "titles_held": "hybrid_phrase_matcher",
    "name": "ner",
    "email": "deterministic",
    "total_experience_years": "deterministic",
    "employers": "ner",
}


def setup_aws(env: str):
    cf = boto3.client("cloudformation", region_name=REGION)
    out = {
        o["OutputKey"]: o["OutputValue"]
        for o in cf.describe_stacks(StackName=f"resume-screener-{env}")["Stacks"][0]["Outputs"]
    }
    ddb = boto3.resource("dynamodb", region_name=REGION)
    return ddb.Table(out["CandidatesTableName"])


def scan_all(table, job_id: str | None = None) -> list[dict]:
    items, last = [], None
    while True:
        kw = {}
        if job_id:
            kw["FilterExpression"] = "job_id = :j"
            kw["ExpressionAttributeValues"] = {":j": job_id}
        if last:
            kw["ExclusiveStartKey"] = last
        resp = table.scan(**kw)
        items.extend(resp.get("Items", []))
        last = resp.get("LastEvaluatedKey")
        if not last:
            break
    return items


def best_match(items: list[dict], filename: str) -> dict | None:
    matches = [
        i for i in items if i.get("original_filename") == filename and i.get("parse_status") == "parsed"
    ]
    if not matches:
        return None
    return max(matches, key=lambda i: i.get("updated_at", ""))


def build_output(item: dict, label: str) -> dict:
    """Build the sample output document from a live DynamoDB item."""
    # extracted_text may or may not be stored; check for it gracefully
    raw_text = item.get("extracted_text") or item.get("raw_text") or ""
    text_truncated = raw_text[:2000] + ("…[truncated]" if len(raw_text) > 2000 else "")

    entities = {
        "name": item.get("name"),
        "email": item.get("email"),
        "skills": list(item.get("skills", [])),
        "titles_held": list(item.get("titles_held", [])),
        "employers": list(item.get("employers", [])),
        "total_experience_years": (
            float(item["total_experience_years"]) if item.get("total_experience_years") is not None else None
        ),
        "experience_estimated": bool(item.get("experience_estimated")),
    }

    extraction_metadata = {
        "file_type": item.get("file_type"),
        "page_count": item.get("page_count"),
        "ocr_applied": item.get("ocr_applied"),
        "char_count": len(raw_text) if raw_text else None,
        "parse_status": item.get("parse_status"),
    }

    return {
        "_notice": "Generated by scripts/capture_sample_output.py — do not hand-edit",
        "_generated_at": datetime.now(UTC).isoformat(),
        "_fixture_type": label,
        "provenance": {
            "job_id": item.get("job_id"),
            "candidate_id": item.get("candidate_id"),
            "original_filename": item.get("original_filename"),
            "updated_at": item.get("updated_at"),
        },
        "extraction_metadata": extraction_metadata,
        "extracted_text": text_truncated if text_truncated else "[not stored in DynamoDB]",
        "entities": entities,
        "method_per_field": METHOD_PER_FIELD,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Capture sample NLP output from deployed stack")
    parser.add_argument("--env", default="dev")
    parser.add_argument("--job-id", default=None, help="Restrict to a specific job (optional)")
    args = parser.parse_args()

    print("Querying DynamoDB for parsed candidates…")
    table = setup_aws(args.env)
    items = scan_all(table, args.job_id)
    print(f"Found {len(items)} items total")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    missing = []

    for label, filename in TARGETS.items():
        item = best_match(items, filename)
        if item is None:
            print(f"  [WARN] No parsed DynamoDB record for {filename} — skipping {label}", file=sys.stderr)
            missing.append(filename)
            continue

        doc = build_output(item, label)
        out_path = OUT_DIR / f"{label}.json"
        out_path.write_text(json.dumps(doc, indent=2, default=str) + "\n", encoding="utf-8")
        print(f"  Written: {out_path}  ({item.get('job_id')})")

    if missing:
        print(f"\nWARNING: {len(missing)} fixture(s) not found in DynamoDB: {missing}")
        print("Run the integration suite first to populate candidate records.")
        return 1

    print("\nAll 3 sample NLP output files written successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
