#!/usr/bin/env bash
# scripts/gen-frontend-env.sh <env>
# Reads live CloudFormation stack outputs and writes frontend/.env.<env>
# Run this whenever the stack is deployed to keep env vars in sync.
set -euo pipefail

ENV="${1:?Usage: gen-frontend-env.sh <env>}"
STACK="resume-screener-${ENV}"
OUT_FILE="frontend/.env.${ENV}"

out() {
  aws cloudformation describe-stacks \
    --stack-name "${STACK}" \
    --query "Stacks[0].Outputs[?OutputKey=='${1}'].OutputValue" \
    --output text
}

API_BASE_URL="$(out ApiBaseUrl)"
USER_POOL_ID="$(out UserPoolId)"
USER_POOL_CLIENT_ID="$(out UserPoolClientId)"
DISTRIBUTION_DOMAIN="$(out DistributionDomain)"

# The bundle talks directly to API Gateway in all environments (CORS is configured
# for both CloudFront and localhost:5173). VITE_API_PROXY_TARGET is retained for
# local Vite dev server proxy compatibility.
VITE_API_BASE_URL="${API_BASE_URL}"
VITE_API_PROXY_TARGET="${API_BASE_URL}"

cat > "${OUT_FILE}" <<EOF
# Generated by scripts/gen-frontend-env.sh ${ENV} — do not commit
VITE_API_BASE_URL=${VITE_API_BASE_URL}
VITE_API_PROXY_TARGET=${VITE_API_PROXY_TARGET}
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
VITE_REGION=ap-south-1
VITE_DISTRIBUTION_DOMAIN=${DISTRIBUTION_DOMAIN}
# Set to true to enable the "Open original resume" link (FR22 / FEATURE_RESUME_VIEW)
VITE_FEATURE_RESUME_VIEW=false
EOF

echo "Written: ${OUT_FILE}"
